name: 'Readme Youtube Last Videos'
description: 'Updates your readme profile with selected youtube channel last videos'
branding:
  icon: user
  color: purple
input:
  max_results:
    description: 'Set the amount of videos to display'
    required: false
    default: 3
  channel_id:
    description: 'The id of the channel to search videos'
    required: true
  entry_file:
    description: 'Template file to render with the videos'
    required: false
    default: './.github/templates/README.md.hbs'
runs:
  using: 'node16'
  main: 'dist/index.js'
