on: [push, workflow_dispatch]
   
jobs:
   update_readme:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - name: Get Youtube Videos
           uses: pmqueiroz/readme-last-youtube-videos@v1.1.2
           env:
              YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
           with:
              channel_id: "UUX6OQ3DkcsbYNE6H8uQQuVA"
              output_file: "EXAMPLE.md"
         - run: |
              git config user.name pmqueiroz
              git config user.email pedroqueiroz593@gmail.com
              git add EXAMPLE.md
              git commit -m "docs: update example through gh action"
              git push origin master
